<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
    <MyType>Empty</MyType>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <StartupObject>KiwoomServer.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.vbproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="AxInterop.KHOpenAPILib">
      <HintPath>C:\Users\haoru\Desktop\2025\Template\lib\AxInterop.KHOpenAPILib.dll</HintPath>
    </Reference>
    <Reference Include="Interop.KHOpenAPILib">
      <HintPath>C:\Users\haoru\Desktop\2025\Template\lib\Interop.KHOpenAPILib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
